export const DICT_CODES = {
  abbr: "abbreviation",
  "adj-f": "noun or verb acting prenominally",
  "adj-i": "i-adjective",
  "adj-kari": "'kari' adjective (archaic)",
  "adj-ku": "'ku' adjective (archaic)",
  "adj-na": "na-adjective",
  "adj-nari": "archaic/formal form of na-adjective",
  "adj-no": "no-adjective",
  "adj-pn": "pre-noun adjectival (rentaishi)",
  "adj-s": "special adjective",
  "adj-shiku": "'shiku' adjective (archaic)",
  "adj-t": "'taru' adjective",
  adv: "adverb",
  "adv-n": "adverbial noun",
  "adv-to": "adverb taking the と particle",
  an: "adjectival noun (keiyoudoushi)",
  anat: "anatomical term",
  arch: "archaism",
  archit: "architecture term",
  astron: "astronomy term",
  ateji: "ateji reading",
  aux: "auxiliary",
  "aux-adj": "auxiliary adjective",
  "aux-v": "auxiliary verb",
  baseb: "baseball term",
  biol: "biology term",
  bot: "botany term",
  Buddh: "Buddhist term",
  bus: "business term",
  c: "company name",
  chem: "chemistry term",
  chn: "children's language",
  col: "colloquialism",
  comp: "computer terminology",
  conj: "conjunction",
  ctr: "counter",
  derog: "derogatory word or expression",
  econ: "economics term",
  eK: "exclusively written in kanji",
  engr: "engineering term",
  exp: "expression",
  f: "female given name",
  fam: "familiar language",
  fem: "female term or language",
  finc: "finance term",
  food: "food term",
  g: "given name, as-yet not classified by sex",
  geol: "geology term",
  geom: "geometry term",
  gikun: "gikun (meaning) reading",
  gram: "grammatical term",
  h: "full (family plus given) name of a person",
  hob: "Hokkaido-ben",
  hon: "honorific language (sonkeigo)",
  hum: "humble language (kenjougo)",
  id: "idiomatic expression",
  ik: "irregular kana",
  iK: "irregular kanji",
  int: "interjection",
  io: "irregular okurigana",
  iv: "irregular verb",
  joc: "jocular, humorous term",
  ksb: "Kansai-ben",
  ktb: "Kantou-ben",
  kyb: "Kyoto-ben",
  kyu: "Kyuushuu-ben",
  law: "law term",
  ling: "linguistics terminology",
  m: "male given name",
  "m-sl": "manga slang",
  MA: "martial arts term",
  male: "male term or language",
  "male-sl": "male slang",
  math: "mathematics",
  med: "medical term",
  mil: "military",
  music: "music term",
  n: "noun",
  "n-adv": "adverbial noun",
  "n-pr": "proper noun",
  "n-pref": "prefix noun",
  "n-suf": "suffix noun",
  "n-t": "temporal noun",
  nab: "Nagano-ben",
  neg: "negative (in a negative sentence, or with negative verb)",
  "neg-v": "negative verb (when used with)",
  num: "numeral",
  o: "organization name",
  obs: "obsolete term",
  obsc: "obscure term",
  ok: "outdated kana",
  oK: "outdated kanji",
  "on-mim": "onomatopoeic or mimetic word",
  osb: "Osaka-ben",
  p: "place-name",
  physics: "physics terminology",
  pn: "pronoun",
  poet: "poetical term",
  pol: "polite language",
  pr: "product name",
  pref: "prefix",
  proverb: "proverb",
  prt: "particle",
  qv: "quod vide (see another entry)",
  rare: "rare",
  rkb: "Ryukyuan language",
  s: "surname",
  sens: "sensitive",
  Shinto: "Shinto term",
  sl: "slang",
  sports: "sports term",
  st: "station name",
  suf: "suffix",
  sumo: "sumo term",
  thb: "Touhoku-ben",
  tsb: "Tosa-ben",
  tsug: "Tsugaru-ben",
  u: "unclassified name",
  uk: "usually written using kana alone",
  uK: "usually written using kanji alone",
  "v-unspec": "verb unspecified",
  v1: "ichidan verb",
  "v2a-s": "nidan verb (archaic)",
  "v2b-k": "nidan verb (archaic)",
  "v2b-s": "nidan verb (archaic)",
  "v2d-k": "nidan verb (archaic)",
  "v2d-s": "nidan verb (archaic)",
  "v2g-k": "nidan verb (archaic)",
  "v2g-s": "nidan verb (archaic)",
  "v2h-k": "nidan verb (archaic)",
  "v2h-s": "nidan verb (archaic)",
  "v2k-k": "nidan verb (archaic)",
  "v2k-s": "nidan verb (archaic)",
  "v2m-k": "nidan verb (archaic)",
  "v2m-s": "nidan verb (archaic)",
  "v2n-s": "nidan verb (archaic)",
  "v2r-k": "nidan verb (archaic)",
  "v2r-s": "nidan verb (archaic)",
  "v2s-s": "nidan verb (archaic)",
  "v2t-k": "nidan verb (archaic)",
  "v2t-s": "nidan verb (archaic)",
  "v2w-s": "nidan verb (archaic)",
  "v2y-k": "nidan verb (archaic)",
  "v2y-s": "nidan verb (archaic)",
  "v2z-s": "nidan verb (archaic)",
  v4b: "yodan verb (archaic)",
  v4g: "yodan verb (archaic)",
  v4h: "yondan verb (archaic)",
  v4k: "yodan verb (archaic)",
  v4m: "yodan verb (archaic)",
  v4n: "yodan verb (archaic)",
  v4r: "yondan verb (archaic)",
  v4s: "yodan verb (archaic)",
  v4t: "yodan verb (archaic)",
  v5aru: "godan verb",
  v5b: "godan verb",
  v5g: "godan verb",
  v5k: "godan verb",
  "v5k-s": "godan verb",
  v5m: "godan verb",
  v5n: "godan verb",
  v5r: "godan verb",
  "v5r-i": "godan verb",
  v5s: "godan verb",
  v5t: "godan verb",
  v5u: "godan verb",
  "v5u-s": "godan verb",
  v5uru: "godan verb",
  v5z: "godan verb",
  vi: "intransitive verb",
  vk: "kuru verb",
  vn: "irregular nu verb",
  vr: "irregular ru verb, plain form ends with -ri",
  vs: "suru verb",
  "vs-c": "su verb - precursor to the modern suru",
  "vs-i": "suru verb - irregular",
  "vs-s": "suru verb - special class",
  vt: "transitive verb",
  vulg: "vulgar expression or word",
  vz: "ichidan verb - -zuru special class (alternative form of -jiru verbs)",
  X: "rude or X-rated term",
  zool: "zoology term"
};
